// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gsubC
std::string gsubC(const std::string& pattern, const std::string& replacement, std::string x);
RcppExport SEXP uavRmp_gsubC(SEXP patternSEXP, SEXP replacementSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type replacement(replacementSEXP);
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(gsubC(pattern, replacement, x));
    return rcpp_result_gen;
END_RCPP
}
// brewPopupRowC
std::string brewPopupRowC(std::string colname, std::string value);
RcppExport SEXP uavRmp_brewPopupRowC(SEXP colnameSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type colname(colnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(brewPopupRowC(colname, value));
    return rcpp_result_gen;
END_RCPP
}
// brewPopupRowAltC
std::string brewPopupRowAltC(std::string colname, std::string value);
RcppExport SEXP uavRmp_brewPopupRowAltC(SEXP colnameSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type colname(colnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(brewPopupRowAltC(colname, value));
    return rcpp_result_gen;
END_RCPP
}
// brewPopupCoords
std::string brewPopupCoords(std::string colname, std::string value);
RcppExport SEXP uavRmp_brewPopupCoords(SEXP colnameSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type colname(colnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(brewPopupCoords(colname, value));
    return rcpp_result_gen;
END_RCPP
}
// mergePopupRows
std::string mergePopupRows(CharacterVector names, CharacterVector values);
RcppExport SEXP uavRmp_mergePopupRows(SEXP namesSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(mergePopupRows(names, values));
    return rcpp_result_gen;
END_RCPP
}
// createTemplate
std::string createTemplate(std::string tmpPath);
RcppExport SEXP uavRmp_createTemplate(SEXP tmpPathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type tmpPath(tmpPathSEXP);
    rcpp_result_gen = Rcpp::wrap(createTemplate(tmpPath));
    return rcpp_result_gen;
END_RCPP
}
// listPopupTemplates
List listPopupTemplates(CharacterMatrix x, CharacterVector names, std::string tmpPath);
RcppExport SEXP uavRmp_listPopupTemplates(SEXP xSEXP, SEXP namesSEXP, SEXP tmpPathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    Rcpp::traits::input_parameter< std::string >::type tmpPath(tmpPathSEXP);
    rcpp_result_gen = Rcpp::wrap(listPopupTemplates(x, names, tmpPath));
    return rcpp_result_gen;
END_RCPP
}
// df2String
CharacterMatrix df2String(DataFrame x);
RcppExport SEXP uavRmp_df2String(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(df2String(x));
    return rcpp_result_gen;
END_RCPP
}
// one2JSON
std::string one2JSON(CharacterVector x);
RcppExport SEXP uavRmp_one2JSON(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(one2JSON(x));
    return rcpp_result_gen;
END_RCPP
}
// all2JSONlist
List all2JSONlist(CharacterMatrix x);
RcppExport SEXP uavRmp_all2JSONlist(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(all2JSONlist(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"uavRmp_gsubC", (DL_FUNC) &uavRmp_gsubC, 3},
    {"uavRmp_brewPopupRowC", (DL_FUNC) &uavRmp_brewPopupRowC, 2},
    {"uavRmp_brewPopupRowAltC", (DL_FUNC) &uavRmp_brewPopupRowAltC, 2},
    {"uavRmp_brewPopupCoords", (DL_FUNC) &uavRmp_brewPopupCoords, 2},
    {"uavRmp_mergePopupRows", (DL_FUNC) &uavRmp_mergePopupRows, 2},
    {"uavRmp_createTemplate", (DL_FUNC) &uavRmp_createTemplate, 1},
    {"uavRmp_listPopupTemplates", (DL_FUNC) &uavRmp_listPopupTemplates, 3},
    {"uavRmp_df2String", (DL_FUNC) &uavRmp_df2String, 1},
    {"uavRmp_one2JSON", (DL_FUNC) &uavRmp_one2JSON, 1},
    {"uavRmp_all2JSONlist", (DL_FUNC) &uavRmp_all2JSONlist, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_uavRmp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
