# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gsubC <- function(pattern, replacement, x) {
    .Call('uavRmp_gsubC', PACKAGE = 'uavRmp', pattern, replacement, x)
}

brewPopupRowC <- function(colname, value) {
    .Call('uavRmp_brewPopupRowC', PACKAGE = 'uavRmp', colname, value)
}

brewPopupRowAltC <- function(colname, value) {
    .Call('uavRmp_brewPopupRowAltC', PACKAGE = 'uavRmp', colname, value)
}

brewPopupCoords <- function(colname, value) {
    .Call('uavRmp_brewPopupCoords', PACKAGE = 'uavRmp', colname, value)
}

mergePopupRows <- function(names, values) {
    .Call('uavRmp_mergePopupRows', PACKAGE = 'uavRmp', names, values)
}

createTemplate <- function(tmpPath) {
    .Call('uavRmp_createTemplate', PACKAGE = 'uavRmp', tmpPath)
}

listPopupTemplates <- function(x, names, tmpPath) {
    .Call('uavRmp_listPopupTemplates', PACKAGE = 'uavRmp', x, names, tmpPath)
}

df2String <- function(x) {
    .Call('uavRmp_df2String', PACKAGE = 'uavRmp', x)
}

one2JSON <- function(x) {
    .Call('uavRmp_one2JSON', PACKAGE = 'uavRmp', x)
}

all2JSONlist <- function(x) {
    .Call('uavRmp_all2JSONlist', PACKAGE = 'uavRmp', x)
}

